<h1 align="center">Oi ğŸ‘‹, Eu sou Pedro Henrique Moreno </h1>
<h3 align="center">Apaixonado por anÃ¡lise e desenvolvimentode dados no mundo digital</h3>

- ğŸ”­ Atualmente estou trabalhando na arÃ©a administrativa

- ğŸŒ± Atualmente estou aprendendo e cursando ** Analise e desenvolvimento de sistema **

- ğŸ“«VocÃª me acha atravÃ©s do e-mail **henriquemoreno601@gmail.com**
